### ISSUE TITLE
pyads Server for testing

### ISSUE THREAD

**Issue by teddyrendahl** [slaclab/pytmc#77]
Stand-up a `pyads.TestServer` to use a mock "PLC" we can then load an EPICS database file and query via Channel Access whether the records respond accordingly.

**Comment by slacAWallace** [comment]
Does this belong in the ADS module testing suite?

**Comment by klauer** [comment]
@slacAWallace My 2c on it: since pytmc is the place we interpret tmc files and make EPICS IOCs, pytmc is probably also the right place for a pyads server that stands up a mock-PLC based on that same TMC file.

**Comment by klauer** [comment]
I've experimented a bit with the pyads-provided server implementation, and it would need a fair amount of work for this to be feasible, sadly.

**Comment by klauer** [comment]
Two paths forward since this issue was opened. In some scenarios one might be chosen over the other:
* (ADS layer) I have some hope for https://github.com/pcdshub/ads-async - but no time to work on it. It has a preliminary ads server that uses .tmc files to create a map of PLC memory + expose symbols over the ADS protocol. It preliminarily works with a real IOC talking to it (see the two open PRs)
* (IOC layer) ads-deploy can auto-create a mock caproto IOC from a TwinCAT project - with no PLC/ADS communication
